[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib/mod.rs"

[[bin]]
name = "aoc"
path = "src/bin/mod.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["derive"] }
rayon = "1.8.0"
