name: CI
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout aoc
        uses: actions/checkout@v2
      - name: unpack old V
        run: unzip v_linux.zip
      - name: Lint
        run: ./v/v fmt -verify exo
      - name: Run tests
        run: ./v/v test exo
      - name: Build
        run: ./v/v -prod aoc.v -o aoc
      - name: Run
        run: ./aoc all
